#!/usr/bin/env bash
# HanryxVault — Bluetooth Receipt Printer Setup
# Pairs a Bluetooth ESC/POS thermal printer and binds it to /dev/rfcomm0
# so the POS server can print receipts over Bluetooth.
#
# Run ONCE after first pairing your printer:
#   sudo bash setup-bluetooth-printer.sh

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[printer]${NC} $*"; }
warn()  { echo -e "${YELLOW}[printer]${NC} $*"; }
error() { echo -e "${RED}[printer]${NC} $*"; exit 1; }

[[ $EUID -ne 0 ]] && error "Run with sudo"

# ── Check bluetooth is available ─────────────────────────────────────────────
command -v bluetoothctl >/dev/null 2>&1 || \
    apt-get install -y --no-install-recommends bluetooth bluez >/dev/null

systemctl enable bluetooth --now || true
sleep 2

# ── Step 1: discover / enter MAC ─────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════"
echo "  HanryxVault Bluetooth Printer Setup"
echo "════════════════════════════════════════════"
echo ""
echo "Turn on your Bluetooth receipt printer now."
echo ""

read -rp "Do you want to scan for the printer? [Y/n]: " SCAN_CHOICE
if [[ "${SCAN_CHOICE,,}" != "n" ]]; then
    info "Scanning for 15 seconds — turn printer's BT on now..."
    timeout 15 bluetoothctl scan on 2>/dev/null || true
    bluetoothctl devices | grep -v "^$" || true
    echo ""
fi

read -rp "Enter printer Bluetooth MAC address (e.g. AA:BB:CC:DD:EE:FF): " BT_MAC

# Validate format
[[ "$BT_MAC" =~ ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$ ]] || \
    error "Invalid MAC address format: $BT_MAC"

RFCOMM_NUM="${1:-0}"          # default to rfcomm0
RFCOMM_DEV="/dev/rfcomm${RFCOMM_NUM}"

# ── Step 2: pair and trust ────────────────────────────────────────────────────
info "Pairing with $BT_MAC..."
bluetoothctl pair    "$BT_MAC" 2>/dev/null || warn "Already paired — continuing"
bluetoothctl trust   "$BT_MAC"
bluetoothctl connect "$BT_MAC" 2>/dev/null || warn "Could not connect right now — will connect on next boot"

# ── Step 3: bind rfcomm ───────────────────────────────────────────────────────
info "Binding $BT_MAC → $RFCOMM_DEV"
rfcomm release "$RFCOMM_NUM" 2>/dev/null || true
rfcomm bind    "$RFCOMM_NUM" "$BT_MAC" 1   # channel 1 (standard SPP)

# ── Step 4: create a systemd service that rebinds on every boot ───────────────
cat > /etc/systemd/system/hanryxvault-rfcomm.service << EOF
[Unit]
Description=HanryxVault Bluetooth Printer rfcomm bind
After=bluetooth.target
Wants=bluetooth.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=/bin/sleep 5
ExecStart=/usr/bin/rfcomm bind ${RFCOMM_NUM} ${BT_MAC} 1
ExecStop=/usr/bin/rfcomm release ${RFCOMM_NUM}
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now hanryxvault-rfcomm.service

# ── Step 5: save config for server.py ────────────────────────────────────────
CONF_PATH="/opt/hanryxvault/printer.conf"
cat > "$CONF_PATH" << EOF
# HanryxVault Printer Configuration
# Auto-generated by setup-bluetooth-printer.sh

# Primary printer path — Bluetooth (rfcomm)
printer_path=/dev/rfcomm${RFCOMM_NUM}
printer_type=bluetooth
printer_bt_mac=${BT_MAC}

# Fallback: USB thermal printer (auto-detected if BT unavailable)
printer_usb_path=/dev/usb/lp0

# Receipt header lines (max 32 chars each for 58mm paper, 42 for 80mm)
receipt_header=HanryxVault
receipt_subheader=Trading Card Shop
receipt_footer=hanryxvault.cards
EOF
chown hanryxvault:hanryxvault "$CONF_PATH" 2>/dev/null || true
info "Saved printer config to $CONF_PATH"

# ── Step 6: test print ───────────────────────────────────────────────────────
echo ""
read -rp "Send a test print? [Y/n]: " TEST_CHOICE
if [[ "${TEST_CHOICE,,}" != "n" ]]; then
    info "Sending test print to $RFCOMM_DEV..."
    # ESC @ = init, ESC a 1 = centre, ESC E 1 = bold
    printf '\x1b@\x1ba\x01\x1bE\x01HanryxVault\x1bE\x00\n' > "$RFCOMM_DEV" 2>/dev/null \
        || warn "Could not write to $RFCOMM_DEV — check printer is on and connected"
    printf 'Printer test OK\n\n\n\n' > "$RFCOMM_DEV" 2>/dev/null || true
    printf '\x1dV\x42\x00' > "$RFCOMM_DEV" 2>/dev/null || true  # cut
fi

echo ""
info "Done! Printer configured:"
info "  Device : $RFCOMM_DEV"
info "  MAC    : $BT_MAC"
info "  Config : $CONF_PATH"
info ""
info "The POS server will now print receipts automatically when the"
info "tablet app calls POST /print/receipt after each sale."
