#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
#  HanryxVault — Trade Show (Satellite) Pi Installer
#
#  Run this on the SECOND (trade show) Pi:
#    sudo bash setup-satellite.sh
#
#  What it does:
#  1. Installs the full POS server stack (identical to the home Pi install)
#  2. Installs the satellite sync agent that runs on every boot
#  3. Prompts for your home Pi URL so it knows where to sync
#
#  The trade show Pi is completely standalone — it works offline at shows.
#  Sync only happens when powered on AND home Pi is reachable.
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="/opt/hanryxvault"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${GREEN}[satellite]${NC} $*"; }
warn()    { echo -e "${YELLOW}[satellite]${NC} $*"; }
step()    { echo -e "${CYAN}══ $* ══${NC}"; }
error()   { echo -e "${RED}[satellite] ERROR:${NC} $*"; exit 1; }

[[ $EUID -ne 0 ]] && error "Run with sudo"

echo ""
echo -e "${CYAN}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║  HanryxVault Satellite Pi Installer     ║"
echo "  ║  Trade Show / Away-Game Setup            ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${NC}"

# ── Step 1: Run main installer ────────────────────────────────────────────────
step "Installing POS server stack"
PARENT_INSTALL="$SCRIPT_DIR/../install.sh"
if [[ -f "$PARENT_INSTALL" ]]; then
    bash "$PARENT_INSTALL"
else
    error "Could not find install.sh at $PARENT_INSTALL — run from the pi-setup/satellite directory"
fi

# ── Step 2: Install satellite sync agent ─────────────────────────────────────
step "Installing satellite sync agent"

cp "$SCRIPT_DIR/satellite_sync.py" "$INSTALL_DIR/satellite_sync.py"
chown hanryxvault:hanryxvault "$INSTALL_DIR/satellite_sync.py"
chmod 644 "$INSTALL_DIR/satellite_sync.py"
info "Installed satellite_sync.py"

# ── Step 3: Configure home Pi URL ─────────────────────────────────────────────
step "Configuring home Pi connection"

echo ""
echo "Enter the URL of your HOME Pi. Options:"
echo "  Via WireGuard VPN : http://10.10.0.1:8080  (most reliable)"
echo "  Via Tailscale     : http://hanryxvault.tailcfc0a3.ts.net"
echo "  Via LAN           : http://192.168.1.50:8080"
echo ""
read -rp "Home Pi URL: " HOME_URL
HOME_URL="${HOME_URL:-http://10.10.0.1:8080}"

CONF_FILE="$INSTALL_DIR/satellite.conf"
cat > "$CONF_FILE" << EOF
# HanryxVault Satellite Configuration — auto-generated by setup-satellite.sh
home_pi_url=${HOME_URL}
timeout_s=15
retry_count=2
EOF
chown hanryxvault:hanryxvault "$CONF_FILE"
info "Saved config: home_pi_url=$HOME_URL"

# ── Step 4: Install systemd sync service ──────────────────────────────────────
step "Installing sync systemd service"

cat > /etc/systemd/system/hanryxvault-satellite-sync.service << 'EOF'
[Unit]
Description=HanryxVault Satellite Sync (push sales, pull inventory)
After=network-online.target hanryxvault.service
Wants=network-online.target
Requires=hanryxvault.service

[Service]
Type=oneshot
User=hanryxvault
WorkingDirectory=/opt/hanryxvault
ExecStart=/opt/hanryxvault/venv/bin/python3 /opt/hanryxvault/satellite_sync.py
StandardOutput=journal
StandardError=journal
SyslogIdentifier=hanryxvault-sync
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable hanryxvault-satellite-sync.service
info "Sync service enabled — will run automatically on every boot"

# ── Step 5: Install barcode daemon ────────────────────────────────────────────
step "Installing Bluetooth/USB barcode scanner daemon"

BARCODE_SRC="$SCRIPT_DIR/../scripts/barcode_daemon.py"
if [[ -f "$BARCODE_SRC" ]]; then
    cp "$BARCODE_SRC" "$INSTALL_DIR/barcode_daemon.py"
    chown root:root "$INSTALL_DIR/barcode_daemon.py"
    chmod 644 "$INSTALL_DIR/barcode_daemon.py"

    "$INSTALL_DIR/venv/bin/pip" install --quiet evdev

    cat > /etc/systemd/system/hanryxvault-barcode.service << 'EOF'
[Unit]
Description=HanryxVault Barcode Scanner Daemon (USB + Bluetooth HID)
After=hanryxvault.service bluetooth.target
Wants=bluetooth.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/hanryxvault
ExecStart=/opt/hanryxvault/venv/bin/python3 /opt/hanryxvault/barcode_daemon.py
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=hanryxvault-barcode

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable --now hanryxvault-barcode.service
    info "Barcode daemon installed and running"
else
    warn "barcode_daemon.py not found — skipping barcode setup"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║  Satellite Pi setup complete!            ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${NC}"
info "Home Pi     : $HOME_URL"
info "Local POS   : http://localhost:8080"
info "Sync runs   : automatically on every boot when home Pi is reachable"
info ""
info "Next steps:"
info "  • Set up Bluetooth printer: sudo bash scripts/setup-bluetooth-printer.sh"
info "  • Pair your BT barcode scanner via: sudo bluetoothctl"
info "    (pair, trust, connect) — the barcode daemon will auto-detect it"
info "  • To trigger a manual sync: sudo systemctl start hanryxvault-satellite-sync"
info "  • View sync logs:           sudo journalctl -u hanryxvault-satellite-sync -f"
